spring:
    datasource:
        url: jdbc:h2:file:./backend/db/data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: admin
        password: password
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    # Disable security for the time being
    autoconfigure:
        exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
    file.name: ./backend/log/backend.log
    level:
        root: INFO
