spring:
  datasource:
    url: jdbc:h2:file:./backend/db/data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
